# Generated by Django 6.1.1 on 2026-10-05 12:08

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import expenses.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=expenses.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('both', 'Income & Expense')], max_length=7)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('position', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=expenses.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0.')])),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='expenses.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
